version: "3.8"
services:
  # Database service
  db: 
    image: postgres:13 
    environment: 
      POSTGRES_DB: ${DB_NAME}            # Database name
      POSTGRES_USER: ${USERNAME}         # Database username
      POSTGRES_PASSWORD: ${PASSWORD}     # Database password

    volumes:
      - pgdata:/var/lib/postgresql/data  # Volume for PostgreSQL data directory

    # Exposing PostgreSQL port
    ports: 
      - "5432:5432"  # Host port:Container port
  # Application service
  app: 
    build: 
      context: .     
      dockerfile: Dockerfile
    environment:
      DB_NAME: ${DB_NAME}      # Database name
      USERNAME: ${USERNAME}    # Database username
      PASSWORD: ${PASSWORD}    # Database password
      HOST: db                 # Database host, set to the name of the db service
      PORT: 5432               # Database port
      BASE_URL: "http://localhost:5000"  # Base URL for the application
    # Exposing application ports
    ports: 
      - "5000:5000"  
      - "8501:8501" 
    depends_on:
      - db  # Ensure the db service is started before the app service
volumes:
  pgdata:  # Volume for PostgreSQL data
